#!/usr/bin/env python3
"""
Deploy WiFi Router Manager - Create standalone executable
"""

import os
import sys
import subprocess
from pathlib import Path

def install_pyinstaller():
    """Install PyInstaller"""
    print("Installing PyInstaller...")
    subprocess.run([sys.executable, "-m", "pip", "install", "pyinstaller"])

def create_executable():
    """Create standalone .exe using PyInstaller"""
    
    print("=" * 60)
    print("  Creating Standalone WiFi Router Manager Executable")
    print("=" * 60)
    print()
    
    # PyInstaller command (Windows uses semicolon for add-data)
    import sys
    separator = ';' if sys.platform == 'win32' else ':'
    
    cmd = [
        'pyinstaller',
        '--onefile',                          # Single executable
        '--noconsole',                        # No console window (use --noconsole instead of --windowed)
        '--name=WiFiRouterManager',           # Executable name
        '--icon=app_icon.ico',                # Application icon
        f'--add-data=mitm_passive_scanner.py{separator}.',  # Include MITM scanner
        f'--add-data=mitm_browser_monitor.py{separator}.',  # Include MITM browser monitor
        f'--add-data=complete_device_discovery.py{separator}.',  # Include discovery
        f'--add-data=device_manager_gui.py{separator}.',     # Include device manager
        f'--add-data=router_manager.py{separator}.',         # Include router manager
        f'--add-data=mdns_ssdp_discovery.py{separator}.',    # Include mDNS/SSDP
        f'--add-data=known_devices.json{separator}.',        # Include database
        f'--add-data=app_icon.ico{separator}.',              # Include icon
        '--hidden-import=scapy',              # Include Scapy
        '--hidden-import=scapy.all',          # Include Scapy modules
        '--hidden-import=scapy.layers.http',  # Include Scapy HTTP layer
        '--hidden-import=scapy.layers.dns',   # Include Scapy DNS layer
        '--hidden-import=tkinter',            # Include Tkinter
        '--collect-all=scapy',                # Collect all Scapy data
        'hybrid_router_gui.py'                # Main script
    ]
    
    print("Running PyInstaller...")
    print(f"Command: {' '.join(cmd)}")
    print()
    
    try:
        result = subprocess.run(cmd, check=True)
        
        print()
        print("=" * 60)
        print("  ✅ Executable Created Successfully!")
        print("=" * 60)
        print()
        print("Location: dist/WiFiRouterManager.exe")
        print()
        print("Next steps:")
        print("  1. Copy WiFiRouterManager.exe to any location")
        print("  2. Double-click to run (will request admin privileges)")
        print("  3. Create desktop shortcut if desired")
        print()
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"❌ PyInstaller failed: {e}")
        return False
    except FileNotFoundError:
        print("❌ PyInstaller not found!")
        print("Installing PyInstaller...")
        install_pyinstaller()
        print("\nPlease run this script again.")
        return False

def create_installer():
    """Create NSIS installer script"""
    
    nsis_script = '''
; WiFi Router Manager Installer Script
; Generated by deploy.py

!include "MUI2.nsh"

Name "WiFi Router Manager"
OutFile "WiFiRouterManager_Setup.exe"
InstallDir "$PROGRAMFILES\\WiFi Router Manager"
RequestExecutionLevel admin

!define MUI_ICON "app_icon.ico"
!define MUI_UNICON "app_icon.ico"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath "$INSTDIR"
    
    File "dist\\WiFiRouterManager.exe"
    File "app_icon.ico"
    
    CreateDirectory "$SMPROGRAMS\\WiFi Router Manager"
    CreateShortCut "$SMPROGRAMS\\WiFi Router Manager\\WiFi Router Manager.lnk" "$INSTDIR\\WiFiRouterManager.exe" "" "$INSTDIR\\app_icon.ico"
    CreateShortCut "$DESKTOP\\WiFi Router Manager.lnk" "$INSTDIR\\WiFiRouterManager.exe" "" "$INSTDIR\\app_icon.ico"
    
    WriteUninstaller "$INSTDIR\\Uninstall.exe"
    
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\WiFiRouterManager" "DisplayName" "WiFi Router Manager"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\WiFiRouterManager" "UninstallString" "$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
    Delete "$INSTDIR\\WiFiRouterManager.exe"
    Delete "$INSTDIR\\app_icon.ico"
    Delete "$INSTDIR\\Uninstall.exe"
    
    Delete "$SMPROGRAMS\\WiFi Router Manager\\WiFi Router Manager.lnk"
    Delete "$DESKTOP\\WiFi Router Manager.lnk"
    
    RMDir "$SMPROGRAMS\\WiFi Router Manager"
    RMDir "$INSTDIR"
    
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\WiFiRouterManager"
SectionEnd
'''
    
    with open('installer.nsi', 'w') as f:
        f.write(nsis_script)
    
    print("✅ NSIS installer script created: installer.nsi")
    print()
    print("To create installer:")
    print("  1. Install NSIS from https://nsis.sourceforge.io/")
    print("  2. Right-click installer.nsi → Compile NSIS Script")
    print("  3. You'll get WiFiRouterManager_Setup.exe")
    print()

def main():
    """Main deployment process"""
    
    print()
    print("=" * 60)
    print("  WiFi Router Manager - Deployment Tool")
    print("=" * 60)
    print()
    
    # Step 1: Create icon
    print("Step 1: Creating application icon...")
    try:
        exec(open('create_app_icon.py').read())
    except Exception as e:
        print(f"Warning: Could not create icon: {e}")
    
    print()
    
    # Step 2: Create executable
    print("Step 2: Creating standalone executable...")
    success = create_executable()
    
    if success:
        # Step 3: Create installer script
        print()
        print("Step 3: Creating installer script...")
        create_installer()
        
        # Step 4: Create desktop shortcut
        print()
        print("Step 4: Creating desktop shortcut...")
        try:
            exec(open('create_desktop_shortcut.py').read())
        except Exception as e:
            print(f"Note: Desktop shortcut creation skipped: {e}")
        
        print()
        print("=" * 60)
        print("  🎉 Deployment Complete!")
        print("=" * 60)
        print()
        print("You now have:")
        print("  ✅ Standalone executable: dist/WiFiRouterManager.exe")
        print("  ✅ Application icon: app_icon.ico")
        print("  ✅ Installer script: installer.nsi")
        print("  ✅ Desktop shortcut (if created)")
        print()
        print("Features included:")
        print("  🌐 Device scanning and management")
        print("  🚫 Block/unblock devices via router API")
        print("  🕵️  MITM Browser Monitor - Real-time web browsing tracker")
        print("  📊 Complete device discovery (NetBIOS, mDNS, SSDP)")
        print("  📝 Device naming and management")
        print()
        print("To distribute:")
        print("  - Simple: Share WiFiRouterManager.exe")
        print("  - Professional: Create installer using NSIS")
        print()
        print("⚠️  Important: MITM features require Administrator privileges")
        print()

if __name__ == "__main__":
    main()
